export const cryptoFieldsPresets = {
  base: {
    rank: true,
    name: true,
    symbol: true,
    image: true,
    price: true,
    ch24h: true,
    ch24h_direction: true,
    ch7d: true,
    ch7d_direction: true,
    marketCap: true,
    volume24h: true,
    spark: true,
    isFavorite: true,
  },
  top: {
    rank: true,
    name: true,
    symbol: true,
    image: true,
    price: true,
    ch24h: true,
    ch24h_direction: true,
    ch7d: true,
    ch7d_direction: true,
    marketCap: true,
    volume24h: true,
    spark: true,
    isFavorite: true,
  },
  favorite: {
    rank: true,
    name: true,
    symbol: true,
    image: true,
    price: true,
    ch24h: true,
    ch24h_direction: true,
    ch7d: true,
    ch7d_direction: true,
    marketCap: true,
    volume24h: true,
    spark: true,
    isFavorite: true,
  },
} as const
