import { NewsTableRow } from '../types.ts'

export const initialNewsRows: NewsTableRow[] = [
  {
    id: '2b9c77e3-3e73-4c81-bf67-0b2e7d2f8f53',
    title: 'Pengu захватил Токио',
    summary: 'Комьюнити устроило встречу у MODI, на билбордах — Пэнгу.',
    publishedAt: '2024-01-01T12:00:00.000Z',
    source: 'PudgyPenguins',
    url: 'https://twitter.com/PudgyPenguins',
    verified: true,
    sourceAvatar: '/cdn/group-avatar/23423-pengu.jpeg',
    image: '/cdn/news-image/050925-pic-pengu.jpg',
    tags: ['nft', 'pengu'],
    isFeatured: true,
    reactions: [
      { type: 'LIKE', count: 30 },
      { type: 'GOOD', count: 1 },
      { type: 'FIRE', count: 1 },
      { type: 'BULL', count: 1 },
      { type: 'CELEBRATION', count: 1 },
      { type: 'FOMO', count: 1 },
    ],
    toolbar: { views: '1K', comments: 1, reposts: 1, smiles: 17 },
  },
  {
    id: 'e1e2d3f4-1111-2222-3333-444455556666',
    title: 'Ethereum gas fees reach yearly low',
    summary: 'Network usage drops, lowering transaction costs.',
    publishedAt: '2024-02-10T09:30:00.000Z',
    source: 'The Block',
    verified: Math.random() > 0.5,
    url: 'https://example.com/news/eth-gas',
    tags: ['crypto', 'eth'],
    reactions: [
      { type: 'LIKE', count: 12 },
      { type: 'FIRE', count: 2 },
    ],
    toolbar: { views: 540, comments: 0, reposts: 0, smiles: 5 },
  },
  {
    id: 'a2b3c4d5-aaaa-bbbb-cccc-ddddeeeeffff',
    title: 'Solana ecosystem expands with new DeFi apps',
    summary: 'Developers ship multiple protocols on SOL.',
    publishedAt: '2024-03-03T14:00:00.000Z',
    source: 'CoinTelegraph',
    verified: Math.random() > 0.5,
    url: 'https://example.com/news/sol-defi',
    tags: ['crypto', 'sol'],
    reactions: [
      { type: 'LIKE', count: 7 },
      { type: 'BULL', count: 1 },
    ],
    toolbar: { views: 320, comments: 2, reposts: 1, smiles: 3 },
  },
  {
    id: '11112222-3333-4444-5555-666677778888',
    title: 'Stablecoin adoption grows among merchants',
    summary: 'Retail payments increasingly use USDT and USDC.',
    publishedAt: '2024-03-20T08:15:00.000Z',
    source: 'Bloomberg',
    url: 'https://example.com/news/stablecoin',
    tags: ['stablecoin', 'payments'],
    reactions: [{ type: 'LIKE', count: 3 }],
    toolbar: { views: 210, comments: 0, reposts: 0, smiles: 1 },
  },
  {
    id: '9999aaaa-bbbb-cccc-dddd-eeeeffff0000',
    title: 'Institutional interest in BTC options rises',
    summary: 'Derivatives markets see record open interest.',
    publishedAt: '2024-04-05T10:45:00.000Z',
    source: 'Reuters',
    url: 'https://example.com/news/options',
    tags: ['btc', 'derivatives'],
    reactions: [
      { type: 'LIKE', count: 5 },
      { type: 'FOMO', count: 1 },
    ],
    toolbar: { views: 400, comments: 1, reposts: 0, smiles: 2 },
  },
  {
    id: '1010fefe-adad-bcbc-cdcd-dedeefef1111',
    title: 'Layer-2 solutions hit new throughput records',
    summary: 'Scaling tech reduces fees and improves UX.',
    publishedAt: '2024-04-12T12:20:00.000Z',
    source: 'Messari',
    url: 'https://example.com/news/l2',
    tags: ['l2', 'scaling'],
    reactions: [{ type: 'LIKE', count: 2 }],
    toolbar: { views: 190, comments: 0, reposts: 0, smiles: 0 },
  },
  {
    id: '2020abab-3434-cdcd-5656-efef7878abab',
    title: 'Major exchange lists new memecoin',
    summary: 'High volatility expected after the listing.',
    publishedAt: '2024-05-01T16:00:00.000Z',
    source: 'Decrypt',
    url: 'https://example.com/news/memecoin',
    tags: ['listing', 'memecoin'],
    reactions: [{ type: 'LIKE', count: 4 }],
    toolbar: { views: 260, comments: 0, reposts: 1, smiles: 1 },
  },
  {
    id: '3030baba-4545-dcdc-6767-fafa9090baba',
    title: 'Regulators propose clearer crypto tax rules',
    summary: 'Draft law aims to simplify reporting.',
    publishedAt: '2024-05-18T11:10:00.000Z',
    source: 'WSJ',
    url: 'https://example.com/news/tax',
    tags: ['regulation', 'tax'],
    reactions: [{ type: 'LIKE', count: 6 }],
    toolbar: { views: 150, comments: 0, reposts: 0, smiles: 0 },
  },
  {
    id: '4040caca-5656-eded-7878-bcbc1010caca',
    title: 'DeFi TVL rebounds after market dip',
    summary: 'Capital flows back into lending protocols.',
    publishedAt: '2024-06-02T07:50:00.000Z',
    source: 'DefiLlama',
    url: 'https://example.com/news/defi-tvl',
    tags: ['defi', 'tvl'],
    reactions: [{ type: 'LIKE', count: 1 }],
    toolbar: { views: 120, comments: 0, reposts: 0, smiles: 0 },
  },
  {
    id: '5050dada-6767-fefe-8989-cdcd1212dada',
    title: 'NFT volumes stabilize across marketplaces',
    summary: 'Blue chip collections lead the activity.',
    publishedAt: '2024-06-15T09:05:00.000Z',
    source: 'OpenSea',
    url: 'https://example.com/news/nft',
    tags: ['nft'],
  },
  {
    id: '6060eaea-7878-aaaa-9a9a-dede1414eaea',
    title: 'Macro outlook boosts risk-on assets',
    summary: 'Markets react to interest rate guidance.',
    publishedAt: '2024-07-01T15:30:00.000Z',
    source: 'FT',
    url: 'https://example.com/news/macro',
    tags: ['macro'],
    reactions: [{ type: 'LIKE', count: 9 }],
    toolbar: { views: 510, comments: 3, reposts: 1, smiles: 4 },
  },
]
